# Generated by Django 6.0.1 on 2026-01-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameProduct', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('productPhoto', models.ImageField(upload_to='mercadinho/media')),
            ],
        ),
    ]
